name: trabahanap-admin
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4=py313hecd8cb5_0
  - aiohttp=3.11.10=py313h46256e1_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py313hecd8cb5_0
  - anyio=4.7.0=py313hecd8cb5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py313h46256e1_1
  - attrs=24.3.0=py313hecd8cb5_0
  - bcrypt=3.2.0=py313h46256e1_2
  - beanie=1.29.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.2.25=hecd8cb5_0
  - certifi=2025.4.26=py313hecd8cb5_0
  - cffi=1.17.1=py313h9205ec4_1
  - click=8.1.8=py313hecd8cb5_0
  - cryptography=44.0.1=py313he15b966_0
  - dnspython=2.4.2=py313hecd8cb5_0
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - expat=2.7.1=h6d0c2b6_0
  - fastapi=0.115.12=pyh29332c3_0
  - fastapi-cli=0.0.7=pyhd8ed1ab_0
  - frozenlist=1.5.0=py313h46256e1_0
  - h11=0.14.0=py313hecd8cb5_0
  - httpcore=1.0.2=py313hecd8cb5_0
  - httptools=0.6.4=py313h46256e1_0
  - httpx=0.27.0=py313hecd8cb5_0
  - idna=3.7=py313hecd8cb5_0
  - jinja2=3.1.6=py313hecd8cb5_0
  - lazy-model=0.2.0=pyhd8ed1ab_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_1
  - libmpdec=4.0.0=h46256e1_0
  - libuv=1.48.0=h46256e1_0
  - markdown-it-py=2.2.0=py313hecd8cb5_1
  - markupsafe=3.0.2=py313h46256e1_0
  - mdurl=0.1.0=py313hecd8cb5_0
  - motor=3.5.1=pyhd8ed1ab_0
  - multidict=6.1.0=py313h46256e1_0
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.16=h184c1cd_0
  - passlib=1.7.4=pyhd8ed1ab_2
  - pip=25.1=pyhc872135_2
  - propcache=0.3.1=py313h46256e1_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.21=py313h0efe6ff_0
  - pydantic-core=2.27.1=py313h83de92b_0
  - pygments=2.19.1=py313hecd8cb5_0
  - pyjwt=2.10.1=py313hecd8cb5_0
  - pymongo=4.8.0=py313h46256e1_0
  - python=3.13.2=h1ec50cd_100_cp313
  - python-dotenv=1.1.0=py313hecd8cb5_0
  - python-multipart=0.0.20=py313hecd8cb5_0
  - python_abi=3.13=0_cp313
  - pyyaml=6.0.2=py313h46256e1_0
  - readline=8.2=hca72f7f_0
  - rich=13.9.4=py313hecd8cb5_0
  - rich-toolkit=0.11.3=pyh29332c3_0
  - setuptools=78.1.1=py313hecd8cb5_0
  - shellingham=1.5.0=py313hecd8cb5_0
  - six=1.17.0=py313hecd8cb5_0
  - sniffio=1.3.0=py313hecd8cb5_0
  - sqlite=3.45.3=h6c40b1e_0
  - starlette=0.46.2=py313hecd8cb5_0
  - tk=8.6.14=h4d00af3_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.4.2=py313h46256e1_0
  - typer=0.15.3=pyhf21524f_0
  - typer-slim=0.15.3=pyh29332c3_0
  - typer-slim-standard=0.15.3=h1a15894_0
  - typing-extensions=4.12.2=py313hecd8cb5_0
  - typing_extensions=4.12.2=py313hecd8cb5_0
  - tzdata=2025b=h04d1e81_0
  - uvicorn=0.32.1=py313hecd8cb5_0
  - uvicorn-standard=0.32.1=py313hecd8cb5_0
  - uvloop=0.21.0=py313h46256e1_0
  - watchfiles=0.24.0=py313h83de92b_2
  - websockets=10.4=py313h46256e1_2
  - wheel=0.45.1=py313hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.18.0=py313h46256e1_0
  - zlib=1.2.13=h4b97444_1
prefix: /opt/anaconda3/envs/trabahanap-admin
